add hotel to trip
chingu-voyages/v45-tier3-team-53 pull request #57
Opened 2023-09-17 22:12 UTC by keldim

2023-09-19 03:39 UTC, shawnkoong requested changes

2023-09-19 03:39 UTC, shawnkoong commented on backend/src/main/java/com/chinguv45tier3team53/tripplannerrest/controller/HotelController.java
i think having better path names would eliminate the need for `ObjectNode`, instead having path params or something like this

2023-09-19 05:36 UTC, keldim commented on backend/src/main/java/com/chinguv45tier3team53/tripplannerrest/controller/HotelController.java
yeah that sounds like a good idea, I'll change it

2023-09-20 00:06 UTC, shawnkoong approved these changes

2023-09-20 00:06 UTC, merged